# -*- mode: ruby -*-
# vi: set ft=ruby : 

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"
  
  config.vm.hostname = "example1"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

end

