# -*- mode: ruby -*-
# vi: set ft=ruby :


# Make sure the plugin installed
unless Vagrant.has_plugin?("vagrant-hostmanager")
    raise 'vagrant-hostmanager plugin is not installed!, install it using this command "vagrant plugin install vagrant-hostmanager"'
end

number_of_vm = 3

Vagrant.configure("2") do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.box = "hashicorp/bionic64"
  
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "2048"
    end

    (1..number_of_vm).each do |i|
        config.vm.define "vm#{i}-example5" do |server|
            server.vm.hostname = "vm#{i}-example5"
            server.vm.network "private_network", ip: "10.0.0.1#{i}"
        end
    end

end